"use strict";
var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
Object.defineProperty(exports, "__esModule", { value: true });
var lit_1 = require("lit");
exports.default = lit_1.css(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n\t:host {\n\t\tflex: 0 0;\n\t}\n\n\tet2-dialog::part(body) {\n\t\tdisplay: flex;\n\t\tflex-direction: column;\n\t\tgap: var(--sl-spacing-small);\n\t}\n    et2-dialog et2-vfs-select-row{\n        overflow-wrap: anywhere;\n    }\n\n\t.et2_toolbar {\n\t\tdisplay: flex;\n\t\tgap: 1ex;\n\t}\n\n\t.et2_toolbar::slotted(*) {\n\t\tflex: 1 1 auto;\n\t}\n\n\t.et2_toolbar::slotted(et2-button) {\n\t\tflex-grow: 0;\n\t}\n\n\t.search__results {\n\t\tflex: 2 1 auto;\n\t\tmin-height: 15em;\n\t\toverflow-y: auto;\n\t}\n\n\t.search__results .search__empty {\n\t\theight: 50%;\n\t\tmin-height: 5em;\n\t\tmin-width: 20em;\n\t\tdisplay: flex;\n\t\tflex-direction: column;\n\t\talign-items: center;\n\t\tfilter: contrast(0.1);\n\t\tuser-select: none;\n\t}\n\n\t.search__results .search__empty et2-image {\n\t\tmargin-top: auto;\n\t}\n\n\t.vfs_select__file_row {\n\t\tdisplay: table-row;\n\t}\n\n\t.search__results .search__loading {\n\t\ttext-align: center;\n\t\tline-height: 15em; // 3 * listbox min height\n\t}\n\n\t.search__results sl-spinner {\n\t\tfont-size: 4rem;\n\t}\n\n\t.search__results .search__more {\n\t\ttext-align: center;\n\t}\n\n\t.vfs_select__mimefilter {\n\t\tflex: 0 0;\n\t}\n\n\t:host::part(form-control-help-text) {\n\t\tflex-basis: min-content !important;\n\t}\n"], ["\n\t:host {\n\t\tflex: 0 0;\n\t}\n\n\tet2-dialog::part(body) {\n\t\tdisplay: flex;\n\t\tflex-direction: column;\n\t\tgap: var(--sl-spacing-small);\n\t}\n    et2-dialog et2-vfs-select-row{\n        overflow-wrap: anywhere;\n    }\n\n\t.et2_toolbar {\n\t\tdisplay: flex;\n\t\tgap: 1ex;\n\t}\n\n\t.et2_toolbar::slotted(*) {\n\t\tflex: 1 1 auto;\n\t}\n\n\t.et2_toolbar::slotted(et2-button) {\n\t\tflex-grow: 0;\n\t}\n\n\t.search__results {\n\t\tflex: 2 1 auto;\n\t\tmin-height: 15em;\n\t\toverflow-y: auto;\n\t}\n\n\t.search__results .search__empty {\n\t\theight: 50%;\n\t\tmin-height: 5em;\n\t\tmin-width: 20em;\n\t\tdisplay: flex;\n\t\tflex-direction: column;\n\t\talign-items: center;\n\t\tfilter: contrast(0.1);\n\t\tuser-select: none;\n\t}\n\n\t.search__results .search__empty et2-image {\n\t\tmargin-top: auto;\n\t}\n\n\t.vfs_select__file_row {\n\t\tdisplay: table-row;\n\t}\n\n\t.search__results .search__loading {\n\t\ttext-align: center;\n\t\tline-height: 15em; // 3 * listbox min height\n\t}\n\n\t.search__results sl-spinner {\n\t\tfont-size: 4rem;\n\t}\n\n\t.search__results .search__more {\n\t\ttext-align: center;\n\t}\n\n\t.vfs_select__mimefilter {\n\t\tflex: 0 0;\n\t}\n\n\t:host::part(form-control-help-text) {\n\t\tflex-basis: min-content !important;\n\t}\n"])));
var templateObject_1;
