<?php
/**
 * EGroupware - eTemplates for Application ai-assistant
 * http://www.egroupware.org
 * generated by soetemplate::dump4setup() 2025-01-23 10:00
 *
 * @license http://opensource.org/licenses/gpl-license.php GPL - GNU General Public License
 * @package ai-assistant
 * @subpackage setup
 * @version $Id$
 */

$templ_version=1;

$templ_data[] = array(
    'name' => 'ai-assistant.chat.interface',
    'template' => '',
    'lang' => '',
    'group' => '0',
    'version' => '1.0',
    'data' => 'a:1:{i:0;a:4:{s:4:"type";s:4:"grid";s:4:"data";a:4:{i:0;a:0:{}i:1;a:1:{s:1:"A";a:2:{s:4:"type";s:5:"label";s:5:"label";s:13:"AI Assistant Chat Interface";}}i:2;a:1:{s:1:"A";a:3:{s:4:"type";s:8:"textarea";s:4:"name";s:12:"chat_history";s:4:"size";s:5:"20,80";}}i:3;a:1:{s:1:"A";a:3:{s:4:"type";s:4:"text";s:4:"name";s:12:"user_message";s:4:"size";s:2:"80";}}}s:4:"rows";i:3;s:4:"cols";i:1;}}',
    'size' => '',
    'style' => '',
    'modified' => '1706026800',
);

$templ_data[] = array(
    'name' => 'ai-assistant.config.form',
    'template' => '',
    'lang' => '',
    'group' => '0', 
    'version' => '1.0',
    'data' => 'a:1:{i:0;a:4:{s:4:"type";s:4:"grid";s:4:"data";a:6:{i:0;a:0:{}i:1;a:1:{s:1:"A";a:2:{s:4:"type";s:5:"label";s:5:"label";s:24:"AI Assistant Configuration";}}i:2;a:2:{s:1:"A";a:2:{s:4:"type";s:5:"label";s:5:"label";s:11:"API URL:";}s:1:"B";a:3:{s:4:"type";s:4:"text";s:4:"name";s:10:"ai_api_url";s:4:"size";s:2:"50";}}i:3;a:2:{s:1:"A";a:2:{s:4:"type";s:5:"label";s:5:"label";s:11:"API Key:";}s:1:"B";a:3:{s:4:"type";s:8:"password";s:4:"name";s:10:"ai_api_key";s:4:"size";s:2:"50";}}i:4;a:2:{s:1:"A";a:2:{s:4:"type";s:5:"label";s:5:"label";s:9:"Model:";}s:1:"B";a:3:{s:4:"type";s:4:"text";s:4:"name";s:8:"ai_model";s:4:"size";s:2:"30";}}i:5;a:2:{s:1:"A";a:2:{s:4:"type";s:6:"button";s:5:"label";s:4:"Save";}s:1:"B";a:2:{s:4:"type";s:6:"button";s:5:"label";s:6:"Cancel";}}}s:4:"rows";i:5;s:4:"cols";i:2;}}',
    'size' => '',
    'style' => '',
    'modified' => '1706026800',
);

$templ_data[] = array(
    'name' => 'ai-assistant.history.list',
    'template' => '',
    'lang' => '',
    'group' => '0',
    'version' => '1.0',
    'data' => 'a:1:{i:0;a:4:{s:4:"type";s:4:"grid";s:4:"data";a:4:{i:0;a:2:{s:2:"c1";s:2:"th";s:2:"c2";s:7:"row,top";}i:1;a:4:{s:1:"A";a:2:{s:4:"type";s:16:"nextmatch-header";s:5:"label";s:19:"Conversation Title";}s:1:"B";a:2:{s:4:"type";s:16:"nextmatch-header";s:5:"label";s:7:"Created";}s:1:"C";a:2:{s:4:"type";s:16:"nextmatch-header";s:5:"label";s:8:"Modified";}s:1:"D";a:2:{s:4:"type";s:16:"nextmatch-header";s:5:"label";s:7:"Actions";}}i:2;a:4:{s:1:"A";a:2:{s:4:"type";s:5:"label";s:4:"name";s:13:"${row}[title]";}s:1:"B";a:2:{s:4:"type";s:9:"date-time";s:4:"name";s:15:"${row}[created]";}s:1:"C";a:2:{s:4:"type";s:9:"date-time";s:4:"name";s:16:"${row}[modified]";}s:1:"D";a:2:{s:4:"type";s:6:"button";s:5:"label";s:4:"View";}}i:3;a:1:{s:1:"A";a:3:{s:4:"type";s:16:"nextmatch-footer";s:4:"span";s:3:"all";s:5:"label";s:5:"Total";}}}s:4:"rows";i:3;s:4:"cols";i:4;}}',
    'size' => '',
    'style' => '',
    'modified' => '1706026800',
);